this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addVest "MNP_Vest_ISRKahki_2";
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_an_m8hc";};
this addBackpack "UK3CB_BAF_B_Carryall_OLI";
for "_i" from 1 to 40 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "rhs_mag_an_m8hc";};
this addHeadgear "rhs_6b28_green_ess";
this addWeapon "arifle_TRG21_F";
this addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "rhsusf_weap_glock17g4";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
