this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addVest "MNP_Vest_ISRKahki_2";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
for "_i" from 1 to 2 do {this addItemToVest "150Rnd_762x51_Box";};
this addBackpack "B_Kitbag_rgr";
this addItemToBackpack "150Rnd_762x51_Box_Tracer";
for "_i" from 1 to 2 do {this addItemToBackpack "150Rnd_762x51_Box";};
this addItemToBackpack "ACE_SpareBarrel";
this addHeadgear "rhs_6b28_green";
this addWeapon "rhs_weap_m240G";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
