this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_MapTools";
this addVest "MNP_Vest_ISRKahki_2";
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m714_White";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_M433_HEDP";};
this addHeadgear "rhs_6b28_green_ess";
this addWeapon "arifle_TRG21_GL_F";
this addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "rhsusf_weap_glock17g4";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
