this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "rhs_mag_9x19mm_7n21_20";
this addVest "MNP_Vest_Light_R3";
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_9x19mm_7n21_20";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m18_green";};
this addItemToVest "ACE_HandFlare_Green";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "rhs_weap_pp2000";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
