this forceAddUniform "rhs_uniform_cu_ucp_10th";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_iotv_ucp_SAW";
for "_i" from 1 to 3 do {this addItemToVest "rhs_200rnd_556x45_T_SAW";};
this addBackpack "usm_pack_200rnd_556_bandoliers";
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_m67";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_Chemlight_HiRed";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Red";};
this addHeadgear "rhsusf_ach_helmet_ESS_ucp";
this addWeapon "rhs_weap_m249_pip";
this addPrimaryWeaponItem "rhsusf_acc_eotech_552";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
