this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 6 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_spcs_ucp";
for "_i" from 1 to 8 do {this addItemToVest "rhsusf_mag_40Rnd_46x30_FMJ";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m18_purple";};
this addBackpack "rhsusf_assault_eagleaiii_ucp";
this addHeadgear "rhsusf_hgu56p";
this addWeapon "rhsusf_weap_MP7A2_grip2";
this addPrimaryWeaponItem "rhsusf_acc_rotex_mp7";
this addPrimaryWeaponItem "rhsusf_acc_M952V";
this addPrimaryWeaponItem "rhsusf_acc_EOTECH";
this addPrimaryWeaponItem "rhsusf_acc_grip2_tan";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
