this forceAddUniform "rhs_uniform_cu_ucp_10th";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "rhs_m136_mag";
this addVest "rhsusf_iotv_ucp_Rifleman";
for "_i" from 1 to 8 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
this addBackpack "usm_pack_200rnd_556_bandoliers";
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_m67";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_Chemlight_HiRed";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Red";};
this addHeadgear "rhsusf_ach_helmet_ESS_ucp";
this addWeapon "rhs_weap_m4a1_carryhandle_mstock_grip2";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15_light";
this addPrimaryWeaponItem "rhsusf_acc_compm4";
this addPrimaryWeaponItem "rhsusf_acc_grip2_tan";
this addWeapon "rhs_weap_M136";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
