this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_RangeTable_82mm";
this addVest "rhsgref_6b23_khaki_rifleman";             
for "_i" from 1 to 4 do {this addItemToVest "rhs_VOG25";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_VG40OP_white";};
for "_i" from 1 to 8 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
this addHeadgear "rhs_ssh68";
this addWeapon "rhs_weap_ak74m_gp25";
this addPrimaryWeaponItem "rhs_acc_dtk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
