this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsgref_6b23_khaki_rifleman";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_f1";};
for "_i" from 1 to 8 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
this addHeadgear "rhs_ssh68";
this addWeapon "rhs_weap_ak74m";
this addPrimaryWeaponItem "rhs_acc_dtk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
