this forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhs_6b23_6sh116";
for "_i" from 1 to 10 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgn";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_white";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_100Rnd_762x54mmR";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhs_weap_ak74m";
this addPrimaryWeaponItem "rhs_acc_dtk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
