this forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 5 do {this addItemToVest "ACE_salineIV_250";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_rdg2_white";};
for "_i" from 1 to 9 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgn";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhs_weap_ak74m";
this addPrimaryWeaponItem "rhs_acc_dtk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
