this forceAddUniform "usm_bdu_d";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "usm_vest_pasgtdes_lbe_rmp";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addBackpack "usm_pack_alice";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_200rnd_556x45_T_SAW";};
this addHeadgear "usm_helmet_pasgt_dcu_m";
this addWeapon "RH_M16A2";
this addPrimaryWeaponItem "acc_flashlight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
