this forceAddUniform "usm_bdu_d";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "usm_vest_pasgtdes_lbe_rmp";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_200rnd_556x45_T_SAW";};
this addHeadgear "usm_helmet_pasgt_dcu_m";
this addWeapon "hlc_lmg_minimipara";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
