this forceAddUniform "MNP_CombatUniform_NOR_D_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "rhsusf_spc_patchless";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_250Rnd_762x51_B_MG3";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_250Rnd_762x51_B_MG3";};
this addItemToBackpack "ACE_SpareBarrel";
this addHeadgear "rhsusf_opscore_ut_pelt";
this addWeapon "hlc_lmg_MG3";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
