this forceAddUniform "UK3CB_BAF_U_Smock_DPMW";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "UK3CB_BAF_V_Osprey_DPMW4";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 6 do {this addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 4 do {this addItemToVest "UK3CB_BAF_556_30Rnd_T";};
this addHeadgear "UK3CB_BAF_H_Mk6_DPMW_A";
this addWeapon "UK3CB_BAF_L85A2";
this addWeapon "rhs_weap_m72a7";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
