this forceAddUniform "UK3CB_BAF_U_CombatUniform_DPMW_ShortSleeve_RM";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "UK3CB_BAF_V_Pilot_DPMW";
for "_i" from 1 to 6 do {this addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_m18_purple";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_HandFlare_Green";};
this addHeadgear "UK3CB_BAF_H_PilotHelmetHeli_A";
this addWeapon "UK3CB_BAF_L22";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhsusf_ANPVS_15";
