this forceAddUniform "U_LIB_GER_Soldier_camo";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "LIB_8Rnd_9x19_P08";
this addVest "V_LIB_GER_VestG43";
for "_i" from 1 to 2 do {this addItemToVest "LIB_shg24";};
this addBackpack "B_LIB_GER_Backpack";
this addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 6 do {this addItemToBackpack "LIB_10Rnd_792x57";};
this addHeadgear "H_LIB_GER_HelmetCamo";
this addWeapon "LIB_G43";
this addWeapon "LIB_P08";
this linkItem "ItemMap";
this linkItem "ItemCompass";
