this forceAddUniform "UK3CB_BAF_U_Smock_Arctic";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "UK3CB_BAF_V_Osprey_Winter";
for "_i" from 1 to 2 do {this addItemToVest "UK3CB_BAF_762_100Rnd_T";};
this addHeadgear "UK3CB_BAF_H_Mk7_Win_ESS_A";
this addGoggles "UK3CB_BAF_G_Balaclava_Win";
this addWeapon "UK3CB_BAF_L7A2";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
