this forceAddUniform "UK3CB_BAF_U_Smock_Arctic";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_RangeTable_82mm";
this addVest "UK3CB_BAF_V_Osprey_Winter";
for "_i" from 1 to 6 do {this addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 4 do {this addItemToVest "UK3CB_BAF_556_30Rnd_T";};
for "_i" from 1 to 5 do {this addItemToVest "UK3CB_BAF_1Rnd_HE_Grenade_Shell";};
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "UK3CB_BAF_H_Mk7_Win_ESS_A";
this addGoggles "UK3CB_BAF_G_Balaclava_Win";
this addWeapon "UK3CB_BAF_L85A2_UGL";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
