this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EntrenchingTool";
this addVest "rhsusf_iotv_ucp_Rifleman";
for "_i" from 1 to 7 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addItemToVest "rhsusf_mag_7x45acp_MHP";
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_smaw_HEAA";};
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_smaw_SR";};
this addHeadgear "rhsusf_ach_bare_tan_headset_ess";
this addWeapon "rhs_weap_m4a1_grip2";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "rhsusf_acc_compm4";
this addPrimaryWeaponItem "rhsusf_acc_grip2";
this addWeapon "rhs_weap_smaw_green";
this addSecondaryWeaponItem "rhs_weap_optic_smaw";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
