this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "rhsusf_iotv_ucp_SAW";
for "_i" from 1 to 2 do {this addItemToVest "hlc_100Rnd_762x51_T_M60E4";};
this addItemToVest "rhsusf_mag_7x45acp_MHP";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addBackpack "rhsusf_assault_eagleaiii_ucp";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "rhsusf_ach_bare_tan_headset_ess";
this addWeapon "hlc_lmg_mk48";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
