this forceAddUniform "rhs_uniform_cu_ucp";
this addVest "rhsusf_iotv_ucp_Rifleman";
for "_i" from 1 to 2 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_RangeTable_82mm";
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addItemToVest "rhs_mag_an_m8hc";
for "_i" from 1 to 3 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "rhs_mag_m67";
this addHeadgear "rhsusf_ach_bare_tan_headset_ess";
this addWeapon "hlc_rifle_Colt727";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
