this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_RangeTable_82mm";
this addVest "rhsusf_iotv_ucp_Rifleman";
for "_i" from 1 to 7 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addItemToVest "rhsusf_mag_7x45acp_MHP";
this addBackpack "rhs_M252_Gun_Bag";
this addHeadgear "rhsusf_ach_bare_tan_headset_ess";
this addWeapon "hlc_rifle_Colt727";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
