this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "hlc_20rnd_762x51_b_G3";};
this addVest "MNP_Vest_Germany_2";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_20rnd_762x51_b_G3";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 7 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_rifle_g3ka4";
this addPrimaryWeaponItem "rhsusf_acc_eotech_xps3";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
