this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 4 do {this addItemToVest "hlc_20rnd_762x51_b_G3";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
this addItemToVest "rhs_mag_m18_green";
this addItemToVest "rhs_mag_m18_red";
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_Smoke_Grenade_shell";};
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 3 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "HLC_Rifle_g3ka4_GL";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_glock17g4";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
