this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 5 do {this addItemToVest "hlc_20rnd_762x51_b_G3";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_20rnd_762x51_t_G3";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 6 do {this addItemToVest "rhs_mag_an_m8hc";};
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 8 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToBackpack "rhs_mag_m18_green";
this addItemToBackpack "rhs_mag_m18_purple";
this addItemToBackpack "rhs_mag_m18_red";
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_rifle_g3ka4";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
