this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_EntrenchingTool";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 4 do {this addItemToVest "hlc_20rnd_762x51_b_G3";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addItemToVest "rhs_mag_m67";
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_smaw_HEAA";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_smaw_SR";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_rifle_g3ka4";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
