this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_50Rnd_792x57_T_MG42";};
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200Rnd_792x57_B_MG42";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_lmg_mg42kws_b";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
