this forceAddUniform "MNP_CombatUniform_Canada_S";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "MNP_Vest_Canada_T";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";};
this addItemToVest "rhs_200rnd_556x45_M_SAW";
this addBackpack "UK3CB_BAF_B_Kitbag_OLI";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_200rnd_556x45_M_SAW";};
this addHeadgear "rhsusf_opscore_fg_pelt";
this addGoggles "rhs_balaclava";
this addWeapon "rhs_weap_m249_pip_L";
this addPrimaryWeaponItem "rhsusf_acc_M2A1";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
