this forceAddUniform "MNP_CombatUniform_Canada";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "Laserbatteries";
this addItemToUniform "ACE_MapTools";
this addVest "MNP_Vest_Canada_T";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 6 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";};
this addHeadgear "H_Cap_headphones";
this addGoggles "rhs_googles_clear";
this addWeapon "rhs_weap_m4_mstock";
this addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
this addPrimaryWeaponItem "UK3CB_BAF_Eotech";
this addWeapon "rhsusf_weap_glock17g4";
this addWeapon "Laserdesignator_03";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
