this forceAddUniform "MNP_CombatUniform_Canada";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "MNP_Vest_Canada_T2";
for "_i" from 1 to 10 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 6 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "rhsusf_opscore_ut_pelt";
this addGoggles "rhs_balaclava";
this addWeapon "rhs_weap_m4_carryhandle";
this addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
this addPrimaryWeaponItem "UK3CB_BAF_Eotech";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
[this,"UK3CB_BAF_Insignia_RedCross"] call bis_fnc_setUnitInsignia;
