this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_SpareBarrel";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addItemToUniform "ACE_EntrenchingTool";
this addVest "rhsusf_spc_iar";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_200rnd_556x45_M_SAW";};
this addBackpack "rhsusf_falconii_coy";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd";
this addWeapon "hlc_lmg_M249E2";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
