this forceAddUniform "usm_bdu_odg";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_LBE_mg_m";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_100Rnd_762x51_T_M60E4";};
this addBackpack "usm_pack_762x51_ammobelts";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "CUP_H_USArmy_Helmet_M1_Olive";
this addWeapon "hlc_lmg_m60";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
