this forceAddUniform "usm_bdu_odg";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_LBE_rmp_m";
for "_i" from 1 to 8 do {this addItemToVest "RH_20Rnd_556x45";};
for "_i" from 1 to 6 do {this addItemToVest "RH_20Rnd_556x45_Red";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "CUP_H_USArmy_Helmet_M1_Olive";
this addWeapon "RH_M16A1gl";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
