this forceAddUniform "MNP_CombatUniform_ISR";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACRE_PRC343_ID_1";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_CableTie";
this addVest "MNP_Vest_Light_R3";
for "_i" from 1 to 4 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addBackpack "UK3CB_BAF_B_Bergen_OLI_Rifleman_A";
for "_i" from 1 to 2 do {this addItemToBackpack "UK3CB_BAF_762_100Rnd";};
this addHeadgear "UK3CB_BAF_H_Mk7_Scrim_E";
this addWeapon "UK3CB_BAF_L7A2";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
