this forceAddUniform "U_LIB_US_Med";
this addItemToUniform "LIB_7Rnd_45ACP";
this addVest "V_LIB_US_Vest_Medic";
for "_i" from 1 to 14 do {this addItemToVest "LIB_8Rnd_762x63";};
this addItemToVest "LIB_US_Mk_2";
this addBackpack "B_LIB_US_M36";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_LIB_US_Helmet_Med";
this addWeapon "LIB_M1_Garand";
this addWeapon "LIB_Colt_M1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
