this forceAddUniform "U_LIB_US_Private";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "LIB_7Rnd_45ACP";
this addVest "V_LIB_US_Vest_45";
for "_i" from 1 to 2 do {this addItemToVest "LIB_US_Mk_2";};
for "_i" from 1 to 16 do {this addItemToVest "LIB_8Rnd_762x63";};
this addBackpack "B_LIB_US_Backpack";
this addItemToBackpack "ACE_EntrenchingTool";
this addHeadgear "H_LIB_US_Helmet_Net";
this addWeapon "LIB_M1_Garand";
this addWeapon "LIB_Colt_M1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
