this forceAddUniform "U_LIB_US_Private";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "LIB_7Rnd_45ACP";
this addVest "V_LIB_US_Vest_Garand";
for "_i" from 1 to 2 do {this addItemToVest "LIB_US_Mk_2";};
for "_i" from 1 to 12 do {this addItemToVest "LIB_15Rnd_762x33";};
this addBackpack "B_LIB_US_Radio";
this addHeadgear "H_LIB_US_Helmet";
this addWeapon "LIB_M1_Carbine";
this addWeapon "LIB_Colt_M1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
