this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addItemToUniform "ACE_EntrenchingTool";
this addVest "rhsusf_spc_mg";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_100Rnd_762x51_m80a1epr";};
this addBackpack "rhsusf_assault_eagleaiii_coy";
for "_i" from 1 to 3 do {this addItemToBackpack "rhsusf_100Rnd_762x51_m80a1epr";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd";
this addWeapon "rhs_weap_m240B";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
