this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "rhs_6b23_ML_6sh92_vog_headset";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_762x39_t_ak";};
this addBackpack "rhs_sidor";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_VOG25P";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_green";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_White";};
this addItemToBackpack "rhs_mag_rgd5";
this addItemToBackpack "rhs_mag_rdg2_white";
this addHeadgear "rhs_ssh68";
this addWeapon "hlc_rifle_akmgl";
this addWeapon "rhs_weap_makarov_pm";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
