this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_RangeTable_82mm";
this addItemToUniform "ACE_MapTools";
this addVest "rhs_6b23_ML_6sh92";
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30Rnd_762x39_t_ak";};
this addHeadgear "rhs_ssh68";
this addWeapon "hlc_rifle_akm";
this addWeapon "rhs_weap_makarov_pm";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
