this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 7 do {this addItemToUniform "";};
this addVest "usm_vest_rba_lbv_gr";
this addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "MiniGrenade";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "ACE_HandFlare_White";
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addItemToBackpack "1Rnd_SmokePurple_Grenade_shell";
for "_i" from 1 to 3 do {this addItemToBackpack "UGL_FlareWhite_F";};
this addItemToBackpack "rhs_mag_m18_purple";
this addItemToBackpack "rhs_mag_m18_red";
this addItemToBackpack "rhs_mag_m18_green";
this addHeadgear "usm_helmet_pasgt_g_w";
this addWeapon "RH_M16A2gl";
this addWeapon "rhsusf_weap_m1911a1";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
