this forceAddUniform "usm_bdu_d";
this addVest "usm_vest_pasgtdes_lbe_rm_m";
for "_i" from 1 to 2 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addItemToVest "rhs_mag_an_m8hc";
for "_i" from 1 to 3 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "rhs_mag_m67";
this addBackpack "B_Carryall_cbr";
this addItemToBackpack "rhs_mag_smaw_HEAA";
this addItemToBackpack "rhs_mag_smaw_HEDP";
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_smaw_SR";};
this addHeadgear "usm_helmet_pasgt_g_dcu_m";
this addWeapon "hlc_rifle_Colt727";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhs_weap_smaw_green";
this addSecondaryWeaponItem "rhs_weap_optic_smaw";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
