this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "";};
this addVest "usm_vest_rba_lbv_mg";
this addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "ACE_HandFlare_White";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Green";};
this addBackpack "usm_pack_alice";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_Mdim_M60E4";};
this addHeadgear "usm_helmet_pasgt_w";
this addWeapon "RH_M16A2";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
