this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 6 do {this addItemToUniform "";};
this addVest "usm_vest_rba_lbe_rm";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_RangeTable_82mm";
this addItemToVest "ACE_RangeCard";
this addItemToVest "ACE_MapTools";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "ACE_HandFlare_White";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
this addHeadgear "usm_helmet_pasgt_w";
this addWeapon "RH_M16A2";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
