this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {this addItemToUniform "";};
this addItemToUniform "rhs_m72a7_mag";
this addVest "usm_vest_rba_lbe_rmp";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
this addItemToVest "rhs_mag_m67";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "ACE_HandFlare_White";
this addHeadgear "usm_helmet_pasgt_g_w_m";
this addWeapon "RH_M16A2";
this addWeapon "rhs_weap_m72a7";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
