this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "";};
this addVest "usm_vest_rba_lbe_rm";
this addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_7x45acp_MHP";};
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "ACE_HandFlare_White";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 3 do {this addItemToVest "rhsusf_5Rnd_00Buck";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_5Rnd_Slug";};
this addHeadgear "usm_helmet_cvc";
this addWeapon "rhs_weap_M590_5RD";
this addWeapon "rhsusf_weap_m1911a1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
