this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_CableTie";
this addVest "rhs_6b23_digi_6sh92_vog_headset";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_VOG25";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_GRD40_White";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_black";};
this addItemToVest "rhs_mag_9x19_17";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_VOG25";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "hlc_rifle_ak12GL";
this addWeapon "rhs_weap_pya";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
