this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_RangeTable_82mm";
this addItemToUniform "rhs_mag_9x19_17";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "rhs_M252_Bipod_Bag";
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "hlc_rifle_ak12";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
