this forceAddUniform "MNP_CombatUniform_Fin_B";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_FIN_1";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_100Rnd_762x54mmR";};
this addHeadgear "MNP_Helmet_FIN_T";
this addWeapon "rhs_weap_pkm";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
