this forceAddUniform "MNP_CombatUniform_Fin_B";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_TacVest_oli";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "ACE_MapTools";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";
for "_i" from 1 to 3 do {this addItemToVest "hlc_20Rnd_762x51_T_fal";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_20Rnd_762x51_B_fal";};
this addBackpack "I_Mortar_01_weapon_F";
this addHeadgear "H_Booniehat_oli";
this addWeapon "hlc_rifle_falosw";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
