this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "UK3CB_BAF_V_Osprey_Winter";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20Rnd_762x51_B_fal";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20Rnd_762x51_T_fal";};
this addBackpack "UK3CB_BAF_B_Bergen_Arctic_Rifleman_A";
for "_i" from 1 to 6 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "MNP_Helmet_FIN_A";
this addWeapon "hlc_rifle_osw_GL";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "rhsusf_acc_compm4";
this addWeapon "rhsusf_weap_m9";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
