this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "UK3CB_BAF_V_Osprey_Winter";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20Rnd_762x51_T_fal";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_20Rnd_762x51_B_fal";};
this addBackpack "UK3CB_BAF_B_Bergen_OLI_Rifleman_A";
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 40 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_tourniquet";};
this addHeadgear "MNP_Helmet_FIN_A";
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_falosw";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
