this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "UK3CB_BAF_V_Osprey_Winter";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
this addBackpack "MNP_B_RUW_CA";
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_100Rnd_762x54mmR";};
this addHeadgear "MNP_Helmet_FIN_A";
this addWeapon "rhs_weap_pkm";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
