this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "UK3CB_BAF_V_Osprey_Winter";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "hlc_rifle_falosw";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
