this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "rhsusf_mag_15Rnd_9x19_JHP";};
this addVest "UK3CB_BAF_V_Osprey_Winter";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_CableTie";
for "_i" from 1 to 3 do {this addItemToVest "hlc_20Rnd_762x51_B_fal";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_20Rnd_762x51_T_fal";};
this addItemToVest "rhs_mag_an_m8hc";
this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_FMJ";};
this addHeadgear "MNP_Helmet_FIN_A";
this addWeapon "hlc_rifle_falosw";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "RKSL_optic_RMR_MS19";
this addWeapon "rhs_weap_M136";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
