this forceAddUniform "MNP_CombatUniform_NOR_A";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "rhsusf_spc_patchless";
for "_i" from 1 to 2 do {this addItemToVest "rhs_200rnd_556x45_T_SAW";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";};
this addItemToVest "rhs_mag_an_m8hc";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_200rnd_556x45_T_SAW";};
this addItemToBackpack "rhs_mag_an_m8hc";
this addHeadgear "rhsusf_opscore_ut_pelt";
this addWeapon "rhs_weap_m249_pip_L_para";
this addPrimaryWeaponItem "rhsusf_acc_compm4";
this addPrimaryWeaponItem "rhsusf_acc_M952V";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
